
UPDATE FormReqDb SET IsApproved = 0 WHERE IsApproved IS NULL;
UPDATE FormReqDb SET IsInvalid = 0 WHERE IsInvalid IS NULL;
ALTER TABLE FormReqDb ALTER COLUMN IsApproved BIT NOT NULL;
ALTER TABLE FormReqDb ALTER COLUMN IsInvalid BIT NOT NULL;
